language: cpp

os:
  - linux
  - osx
  - windows

compiler:
  - gcc
  - clang

script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DPEGTOOL_TESTS=1
  - cmake --build . --config Release
  - ctest -C Release --output-on-failure
